<?php
$nutrition_data = [
    // Breakfast Items (15)
    [
        'name' => 'Kiribath with Lunumiris',
        'type' => 'Breakfast',
        'calories' => 420,
        'protein' => 8.0,
        'carbs' => 65.0,
        'fats' => 15.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['maintenance'],
        'suggestion' => 'Traditional milk rice with spicy sambal. Good for special occasions.',
        'image' => 'images/kiribath.jpg'
    ],
    [
        'name' => 'Hoppers (Appa) with Egg',
        'type' => 'Breakfast',
        'calories' => 280,
        'protein' => 10.0,
        'carbs' => 35.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Fermented rice flour bowl with egg center. Low in calories.',
        'image' => 'images/hopper_egg.jpg'
    ],
    [
        'name' => 'String Hoppers (Idiyappam) with Coconut Sambal',
        'type' => 'Breakfast',
        'calories' => 320,
        'protein' => 5.0,
        'carbs' => 60.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['maintenance'],
        'suggestion' => 'Steamed rice noodles with grated coconut sambal. Gluten-free option.',
        'image' => 'images/string_hoppers.jpg'
    ],
    [
        'name' => 'Pittu with Coconut and Potato Curry',
        'type' => 'Breakfast',
        'calories' => 380,
        'protein' => 7.0,
        'carbs' => 55.0,
        'fats' => 15.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Steamed rice and coconut cylinders with potato curry.',
        'image' => 'images/pittu.jpg'
    ],
    [
        'name' => 'Roti with Dhal Curry',
        'type' => 'Breakfast',
        'calories' => 350,
        'protein' => 12.0,
        'carbs' => 45.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance', 'muscle gain'],
        'suggestion' => 'Whole wheat flatbread with lentil curry. Good protein source.',
        'image' => 'images/roti_dhal.jpg'
    ],
    [
        'name' => 'Kola Kenda (Herbal Porridge)',
        'type' => 'Breakfast',
        'calories' => 180,
        'protein' => 6.0,
        'carbs' => 30.0,
        'fats' => 4.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Diabetes, High Cholesterol',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'detox'],
        'suggestion' => 'Traditional herbal rice porridge with medicinal leaves. Detoxifying.',
        'image' => 'images/kola_kenda.jpg'
    ],
    [
        'name' => 'Uppuma (Spiced Semolina)',
        'type' => 'Breakfast',
        'calories' => 300,
        'protein' => 8.0,
        'carbs' => 45.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Savory semolina cooked with vegetables and spices.',
        'image' => 'images/uppuma.jpg'
    ],
    [
        'name' => 'Coconut Roti with Onion and Chili',
        'type' => 'Breakfast',
        'calories' => 320,
        'protein' => 6.0,
        'carbs' => 35.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['maintenance'],
        'suggestion' => 'Coconut infused flatbread with onions and chilies.',
        'image' => 'images/coconut_roti.jpg'
    ],
    [
        'name' => 'Mung Bean Porridge',
        'type' => 'Breakfast',
        'calories' => 250,
        'protein' => 12.0,
        'carbs' => 35.0,
        'fats' => 6.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Diabetes, Heart Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'detox'],
        'suggestion' => 'Protein-rich mung bean porridge with coconut milk.',
        'image' => 'images/mung_porridge.jpg'
    ],
    [
        'name' => 'Egg Hopper with Coconut Sambal',
        'type' => 'Breakfast',
        'calories' => 290,
        'protein' => 11.0,
        'carbs' => 30.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Crispy bowl-shaped pancake with egg and coconut sambal.',
        'image' => 'images/egg_hopper.jpg'
    ],
    [
        'name' => 'Pol Roti with Seeni Sambol',
        'type' => 'Breakfast',
        'calories' => 340,
        'protein' => 5.0,
        'carbs' => 40.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['maintenance'],
        'suggestion' => 'Coconut flatbread with caramelized onion relish.',
        'image' => 'images/pol_roti.jpg'
    ],
    [
        'name' => 'Dosa with Coconut Chutney',
        'type' => 'Breakfast',
        'calories' => 280,
        'protein' => 8.0,
        'carbs' => 45.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Fermented lentil and rice crepe with coconut chutney.',
        'image' => 'images/dosa.jpg'
    ],
    [
        'name' => 'Vegetable Roti',
        'type' => 'Breakfast',
        'calories' => 320,
        'protein' => 7.0,
        'carbs' => 35.0,
        'fats' => 17.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Flaky pastry filled with spiced vegetables.',
        'image' => 'images/vegetable_roti.jpg'
    ],
    [
        'name' => 'Yellow Rice with Coconut Milk',
        'type' => 'Breakfast',
        'calories' => 380,
        'protein' => 6.0,
        'carbs' => 60.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['maintenance'],
        'suggestion' => 'Fragrant rice cooked in coconut milk with turmeric.',
        'image' => 'images/yellow_rice.jpg'
    ],
    [
        'name' => 'Green Gram Curry with Roti',
        'type' => 'Breakfast',
        'calories' => 350,
        'protein' => 14.0,
        'carbs' => 40.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Moderately Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Protein-rich green gram curry with whole wheat roti.',
        'image' => 'images/green_gram_curry.jpg'
    ],

    // Lunch Items (25)
    [
        'name' => 'Rice and Curry (Chicken)',
        'type' => 'Lunch',
        'calories' => 650,
        'protein' => 30.0,
        'carbs' => 80.0,
        'fats' => 20.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance', 'muscle gain'],
        'suggestion' => 'Traditional Sri Lankan rice with chicken curry and side dishes.',
        'image' => 'images/rice_chicken_curry.jpg'
    ],
    [
        'name' => 'Rice and Curry (Fish)',
        'type' => 'Lunch',
        'calories' => 600,
        'protein' => 25.0,
        'carbs' => 80.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance', 'heart health'],
        'suggestion' => 'Traditional rice with fish curry. Rich in omega-3 fatty acids.',
        'image' => 'images/rice_fish_curry.jpg'
    ],
    [
        'name' => 'Rice and Curry (Vegetable)',
        'type' => 'Lunch',
        'calories' => 500,
        'protein' => 15.0,
        'carbs' => 85.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Rice with assortment of vegetable curries. Plant-based nutrition.',
        'image' => 'images/rice_vegetable_curry.jpg'
    ],
    [
        'name' => 'Lamprais',
        'type' => 'Lunch',
        'calories' => 750,
        'protein' => 35.0,
        'carbs' => 85.0,
        'fats' => 28.0,
        'min_age' => 18,
        'max_age' => 65,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Active',
        'goal' => ['muscle gain'],
        'suggestion' => 'Dutch-influenced rice and curry package baked in banana leaf.',
        'image' => 'images/lamprais.jpg'
    ],
    [
        'name' => 'Biryani (Chicken)',
        'type' => 'Lunch',
        'calories' => 700,
        'protein' => 40.0,
        'carbs' => 90.0,
        'fats' => 20.0,
        'min_age' => 18,
        'max_age' => 65,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Active',
        'goal' => ['muscle gain', 'maintenance'],
        'suggestion' => 'Fragrant spiced rice with chicken. Special occasion dish.',
        'image' => 'images/chicken_biryani.jpg'
    ],
    [
        'name' => 'Biryani (Vegetable)',
        'type' => 'Lunch',
        'calories' => 550,
        'protein' => 18.0,
        'carbs' => 95.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Spiced vegetable rice with nuts and raisins.',
        'image' => 'images/vegetable_biryani.jpg'
    ],
    [
        'name' => 'Kottu Roti (Chicken)',
        'type' => 'Lunch',
        'calories' => 680,
        'protein' => 35.0,
        'carbs' => 70.0,
        'fats' => 25.0,
        'min_age' => 18,
        'max_age' => 65,
        'max_bmi' => 32,
        'gender' => ['Male'],
        'disease' => 'No Disease',
        'activity_level' => 'Very Active',
        'goal' => ['muscle gain'],
        'suggestion' => 'Chopped roti with vegetables, egg, and chicken. Sri Lankan street food favorite.',
        'image' => 'images/chicken_kottu.jpg'
    ],
    [
        'name' => 'Kottu Roti (Vegetable)',
        'type' => 'Lunch',
        'calories' => 520,
        'protein' => 18.0,
        'carbs' => 75.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Chopped roti with mixed vegetables and spices.',
        'image' => 'images/vegetable_kottu.jpg'
    ],
    [
        'name' => 'Jackfruit Curry with Rice',
        'type' => 'Lunch',
        'calories' => 480,
        'protein' => 12.0,
        'carbs' => 85.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Young jackfruit cooked in spices. Meat-like texture, plant-based.',
        'image' => 'images/jackfruit_curry.jpg'
    ],
    [
        'name' => 'Crab Curry with Rice',
        'type' => 'Lunch',
        'calories' => 580,
        'protein' => 40.0,
        'carbs' => 75.0,
        'fats' => 15.0,
        'min_age' => 18,
        'max_age' => 70,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['muscle gain', 'maintenance'],
        'suggestion' => 'Spicy crab curry with rice. Rich in protein and minerals.',
        'image' => 'images/crab_curry.jpg'
    ],
    [
        'name' => 'Prawn Curry with Rice',
        'type' => 'Lunch',
        'calories' => 560,
        'protein' => 35.0,
        'carbs' => 75.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 70,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['muscle gain', 'maintenance'],
        'suggestion' => 'Creamy prawn curry with rice. Good source of selenium.',
        'image' => 'images/prawn_curry.jpg'
    ],
    [
        'name' => 'Beef Curry with Rice',
        'type' => 'Lunch',
        'calories' => 720,
        'protein' => 45.0,
        'carbs' => 80.0,
        'fats' => 25.0,
        'min_age' => 20,
        'max_age' => 60,
        'max_bmi' => 30,
        'gender' => ['Male'],
        'disease' => 'No Disease',
        'activity_level' => 'Very Active',
        'goal' => ['muscle gain'],
        'suggestion' => 'Spicy beef curry with rice. High in protein and iron.',
        'image' => 'images/beef_curry.jpg'
    ],
    [
        'name' => 'Dhal Curry with Rice and Papadum',
        'type' => 'Lunch',
        'calories' => 520,
        'protein' => 20.0,
        'carbs' => 85.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Lentil curry with rice and crispy papadum. Complete protein source.',
        'image' => 'images/dhal_rice.jpg'
    ],
    [
        'name' => 'Egg Curry with Rice',
        'type' => 'Lunch',
        'calories' => 580,
        'protein' => 25.0,
        'carbs' => 80.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance', 'muscle gain'],
        'suggestion' => 'Boiled eggs in spicy gravy with rice. Economical protein source.',
        'image' => 'images/egg_curry.jpg'
    ],
    [
        'name' => 'Mutton Curry with Rice',
        'type' => 'Lunch',
        'calories' => 700,
        'protein' => 40.0,
        'carbs' => 80.0,
        'fats' => 26.0,
        'min_age' => 20,
        'max_age' => 60,
        'max_bmi' => 30,
        'gender' => ['Male'],
        'disease' => 'No Disease',
        'activity_level' => 'Very Active',
        'goal' => ['muscle gain'],
        'suggestion' => 'Rich mutton curry with rice. High in protein and B vitamins.',
        'image' => 'images/mutton_curry.jpg'
    ],
    [
        'name' => 'Brindhal Curry with Rice',
        'type' => 'Lunch',
        'calories' => 450,
        'protein' => 8.0,
        'carbs' => 85.0,
        'fats' => 9.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Eggplant cooked in spices with rice. Low calorie option.',
        'image' => 'images/brindhal_curry.jpg'
    ],
    [
        'name' => 'Okra Curry with Rice',
        'type' => 'Lunch',
        'calories' => 420,
        'protein' => 10.0,
        'carbs' => 75.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Diabetes',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Okra cooked with minimal oil. Good for blood sugar control.',
        'image' => 'images/okra_curry.jpg'
    ],
    [
        'name' => 'Pumpkin Curry with Rice',
        'type' => 'Lunch',
        'calories' => 400,
        'protein' => 7.0,
        'carbs' => 80.0,
        'fats' => 6.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Diabetes',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Sweet pumpkin curry with rice. Rich in vitamin A.',
        'image' => 'images/pumpkin_curry.jpg'
    ],
    [
        'name' => 'Cabbage Curry with Rice',
        'type' => 'Lunch',
        'calories' => 380,
        'protein' => 8.0,
        'carbs' => 70.0,
        'fats' => 7.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'detox'],
        'suggestion' => 'Stir-fried cabbage with rice. High in fiber and vitamin K.',
        'image' => 'images/cabbage_curry.jpg'
    ],
    [
        'name' => 'Beetroot Curry with Rice',
        'type' => 'Lunch',
        'calories' => 420,
        'protein' => 9.0,
        'carbs' => 80.0,
        'fats' => 7.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Anemia',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance', 'heart health'],
        'suggestion' => 'Beetroot cooked in light gravy. Good for blood health.',
        'image' => 'images/beetroot_curry.jpg'
    ],
    [
        'name' => 'Bitter Gourd Curry with Rice',
        'type' => 'Lunch',
        'calories' => 350,
        'protein' => 10.0,
        'carbs' => 65.0,
        'fats' => 6.0,
        'min_age' => 25,
        'max_age' => 75,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Diabetes',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'blood sugar control'],
        'suggestion' => 'Bitter gourd cooked with spices. Excellent for diabetes management.',
        'image' => 'images/bitter_gourd_curry.jpg'
    ],
    [
        'name' => 'Gotukola Sambol with Rice',
        'type' => 'Lunch',
        'calories' => 380,
        'protein' => 12.0,
        'carbs' => 70.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'detox'],
        'suggestion' => 'Centella asiatica salad with rice. Known for cognitive benefits.',
        'image' => 'images/gotukola_sambol.jpg'
    ],
    [
        'name' => 'Mallung with Rice',
        'type' => 'Lunch',
        'calories' => 350,
        'protein' => 15.0,
        'carbs' => 60.0,
        'fats' => 7.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'detox'],
        'suggestion' => 'Chopped greens with coconut. High in iron and antioxidants.',
        'image' => 'images/mallung.jpg'
    ],
    [
        'name' => 'Polos (Young Jackfruit) Curry with Rice',
        'type' => 'Lunch',
        'calories' => 480,
        'protein' => 12.0,
        'carbs' => 85.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Young jackfruit cooked as a meat alternative. High in fiber.',
        'image' => 'images/polos_curry.jpg'
    ],
    [
        'name' => 'Squid Curry with Rice',
        'type' => 'Lunch',
        'calories' => 520,
        'protein' => 38.0,
        'carbs' => 75.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 70,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['muscle gain', 'maintenance'],
        'suggestion' => 'Squid cooked in rich gravy with rice. Excellent source of protein.',
        'image' => 'images/squid_curry.jpg'
    ],

    // Dinner Items (20)
    [
        'name' => 'String Hoppers with Fish Curry',
        'type' => 'Dinner',
        'calories' => 480,
        'protein' => 25.0,
        'carbs' => 65.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Steamed rice noodles with fish curry. Lighter dinner option.',
        'image' => 'images/string_hoppers_fish.jpg'
    ],
    [
        'name' => 'Hoppers with Coconut Sambal',
        'type' => 'Dinner',
        'calories' => 320,
        'protein' => 8.0,
        'carbs' => 45.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Crispy rice flour bowls with coconut sambal. Light dinner.',
        'image' => 'images/hoppers_coconut.jpg'
    ],
    [
        'name' => 'Red Rice with Tempered Fish',
        'type' => 'Dinner',
        'calories' => 520,
        'protein' => 30.0,
        'carbs' => 70.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance', 'muscle gain'],
        'suggestion' => 'Nutritious red rice with pan-fried fish. High in antioxidants.',
        'image' => 'images/red_rice_fish.jpg'
    ],
    [
        'name' => 'Chicken Korma with Naan',
        'type' => 'Dinner',
        'calories' => 680,
        'protein' => 40.0,
        'carbs' => 60.0,
        'fats' => 28.0,
        'min_age' => 18,
        'max_age' => 65,
        'max_bmi' => 30,
        'gender' => ['Male'],
        'disease' => 'No Disease',
        'activity_level' => 'Active',
        'goal' => ['muscle gain'],
        'suggestion' => 'Creamy chicken curry with soft naan bread. Rich and satisfying.',
        'image' => 'images/chicken_korma.jpg'
    ],
    [
        'name' => 'Vegetable Fried Rice',
        'type' => 'Dinner',
        'calories' => 480,
        'protein' => 15.0,
        'carbs' => 75.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Stir-fried rice with mixed vegetables. Quick and easy dinner.',
        'image' => 'images/vegetable_fried_rice.jpg'
    ],
    [
        'name' => 'Dhal Soup with Bread',
        'type' => 'Dinner',
        'calories' => 380,
        'protein' => 18.0,
        'carbs' => 55.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Lentil soup with whole wheat bread. Light and nutritious.',
        'image' => 'images/dhal_soup.jpg'
    ],
    [
        'name' => 'Fish Ambul Thiyal (Sour Fish Curry)',
        'type' => 'Dinner',
        'calories' => 450,
        'protein' => 35.0,
        'carbs' => 40.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Traditional sour fish curry without coconut milk. Unique flavor.',
        'image' => 'images/ambul_thiyal.jpg'
    ],
    [
        'name' => 'Chicken Stir Fry with Rice',
        'type' => 'Dinner',
        'calories' => 520,
        'protein' => 35.0,
        'carbs' => 60.0,
        'fats' => 16.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['muscle gain', 'maintenance'],
        'suggestion' => 'Quick chicken stir fry with rice. Lower in calories than curry.',
        'image' => 'images/chicken_stir_fry.jpg'
    ],
    [
        'name' => 'Vegetable Kottu',
        'type' => 'Dinner',
        'calories' => 480,
        'protein' => 15.0,
        'carbs' => 70.0,
        'fats' => 16.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Chopped roti with vegetables. Popular street food option.',
        'image' => 'images/vegetable_kottu_dinner.jpg'
    ],
    [
        'name' => 'Parippu (Dhal) with Roti',
        'type' => 'Dinner',
        'calories' => 420,
        'protein' => 20.0,
        'carbs' => 55.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Lentil curry with whole wheat roti. Protein-packed dinner.',
        'image' => 'images/parippu_roti.jpg'
    ],
    [
        'name' => 'Mackerel Curry with Rice',
        'type' => 'Dinner',
        'calories' => 520,
        'protein' => 32.0,
        'carbs' => 65.0,
        'fats' => 16.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['maintenance', 'muscle gain'],
        'suggestion' => 'Oily fish curry with rice. Rich in omega-3 fatty acids.',
        'image' => 'images/mackerel_curry.jpg'
    ],
    [
        'name' => 'Chicken Curry with String Hoppers',
        'type' => 'Dinner',
        'calories' => 500,
        'protein' => 35.0,
        'carbs' => 55.0,
        'fats' => 16.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Moderately Active',
        'goal' => ['muscle gain', 'maintenance'],
        'suggestion' => 'Steamed rice noodles with chicken curry. Lighter than rice.',
        'image' => 'images/string_hoppers_chicken.jpg'
    ],
    [
        'name' => 'Vegetable Curry with Pittu',
        'type' => 'Dinner',
        'calories' => 450,
        'protein' => 12.0,
        'carbs' => 70.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Steamed rice and coconut cylinders with vegetable curry.',
        'image' => 'images/pittu_vegetable.jpg'
    ],
    [
        'name' => 'Egg Fried Rice',
        'type' => 'Dinner',
        'calories' => 520,
        'protein' => 20.0,
        'carbs' => 70.0,
        'fats' => 18.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Fried rice with egg and vegetables. Quick protein source.',
        'image' => 'images/egg_fried_rice.jpg'
    ],
    [
        'name' => 'Dhal with Red Rice',
        'type' => 'Dinner',
        'calories' => 450,
        'protein' => 18.0,
        'carbs' => 75.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Lentil curry with nutritious red rice. High in fiber.',
        'image' => 'images/dhal_red_rice.jpg'
    ],
    [
        'name' => 'Chicken Salad with Sri Lankan Dressing',
        'type' => 'Dinner',
        'calories' => 320,
        'protein' => 35.0,
        'carbs' => 15.0,
        'fats' => 14.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss'],
        'suggestion' => 'Grilled chicken with local greens and spicy dressing. Low carb.',
        'image' => 'images/chicken_salad.jpg'
    ],
    [
        'name' => 'Tempered Dhal with Roti',
        'type' => 'Dinner',
        'calories' => 380,
        'protein' => 20.0,
        'carbs' => 50.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Tempered lentil curry with whole wheat roti. Light dinner.',
        'image' => 'images/tempered_dhal.jpg'
    ],
    [
        'name' => 'Vegetable Soup with Bread',
        'type' => 'Dinner',
        'calories' => 280,
        'protein' => 10.0,
        'carbs' => 40.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss'],
        'suggestion' => 'Mixed vegetable soup with whole wheat bread. Very low calorie.',
        'image' => 'images/vegetable_soup.jpg'
    ],
    [
        'name' => 'Fish Cutlets with Salad',
        'type' => 'Dinner',
        'calories' => 420,
        'protein' => 25.0,
        'carbs' => 30.0,
        'fats' => 22.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Spicy fish patties with fresh salad. Good protein source.',
        'image' => 'images/fish_cutlets.jpg'
    ],
    [
        'name' => 'Chicken Wrap with Sri Lankan Spices',
        'type' => 'Dinner',
        'calories' => 380,
        'protein' => 30.0,
        'carbs' => 35.0,
        'fats' => 15.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['weight loss', 'maintenance'],
        'suggestion' => 'Grilled chicken in whole wheat wrap with local spices.',
        'image' => 'images/chicken_wrap.jpg'
    ],

    // Snacks and Desserts (20)
    [
        'name' => 'Vadai (Lentil Fritters)',
        'type' => 'Snack',
        'calories' => 180,
        'protein' => 8.0,
        'carbs' => 20.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Crispy lentil fritters with spices. Popular tea-time snack.',
        'image' => 'images/vadai.jpg'
    ],
    [
        'name' => 'Egg Roll',
        'type' => 'Snack',
        'calories' => 220,
        'protein' => 10.0,
        'carbs' => 20.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Flatbread wrapped around spiced egg mixture. Street food favorite.',
        'image' => 'images/egg_roll.jpg'
    ],
    [
        'name' => 'Samosa',
        'type' => 'Snack',
        'calories' => 200,
        'protein' => 6.0,
        'carbs' => 22.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Triangular pastry filled with spiced potatoes. Popular snack.',
        'image' => 'images/samosa.jpg'
    ],
    [
        'name' => 'Ulundu Vadai (Urad Dal Fritters)',
        'type' => 'Snack',
        'calories' => 190,
        'protein' => 9.0,
        'carbs' => 18.0,
        'fats' => 9.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Donut-shaped lentil fritters. Crispy exterior, soft interior.',
        'image' => 'images/ulundu_vadai.jpg'
    ],
    [
        'name' => 'Parippu Vadai (Dhal Fritters)',
        'type' => 'Snack',
        'calories' => 170,
        'protein' => 8.0,
        'carbs' => 16.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Chana dal fritters with herbs and spices. Protein-rich snack.',
        'image' => 'images/parippu_vadai.jpg'
    ],
    [
        'name' => 'Fish Bun',
        'type' => 'Snack',
        'calories' => 250,
        'protein' => 12.0,
        'carbs' => 25.0,
        'fats' => 12.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Bread filled with spiced fish mixture. Baked or fried.',
        'image' => 'images/fish_bun.jpg'
    ],
    [
        'name' => 'Cutlet (Chicken or Fish)',
        'type' => 'Snack',
        'calories' => 200,
        'protein' => 15.0,
        'carbs' => 12.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'No Disease',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Spiced meat or fish patties coated in breadcrumbs. Protein snack.',
        'image' => 'images/cutlet.jpg'
    ],
    [
        'name' => 'Achcharu (Pickled Fruits)',
        'type' => 'Snack',
        'calories' => 80,
        'protein' => 1.0,
        'carbs' => 18.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss'],
        'suggestion' => 'Pickled fruits with chili and spices. Low calorie snack.',
        'image' => 'images/achcharu.jpg'
    ],
    [
        'name' => 'Konda Kavum (Oil Cake)',
        'type' => 'Snack',
        'calories' => 220,
        'protein' => 3.0,
        'carbs' => 30.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Traditional sweet rice flour cake. Festive treat.',
        'image' => 'images/konda_kavum.jpg'
    ],
    [
        'name' => 'Kokis (Crispy Crunch)',
        'type' => 'Snack',
        'calories' => 180,
        'protein' => 2.0,
        'carbs' => 20.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Deep-fried crispy snack made from rice flour. Traditional festive food.',
        'image' => 'images/kokis.jpg'
    ],
    [
        'name' => 'Aluwa (Rice Flour Sweet)',
        'type' => 'Snack',
        'calories' => 200,
        'protein' => 3.0,
        'carbs' => 40.0,
        'fats' => 4.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Diamond-shaped rice flour sweet. Traditional Sri Lankan sweetmeat.',
        'image' => 'images/aluwa.jpg'
    ],
    [
        'name' => 'Weli Thalapa (Rice Flour Cake)',
        'type' => 'Snack',
        'calories' => 180,
        'protein' => 4.0,
        'carbs' => 35.0,
        'fats' => 3.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Steamed rice flour cake wrapped in leaves. Healthy snack option.',
        'image' => 'images/weli_thalapa.jpg'
    ],
    [
        'name' => 'Thala Guli (Sesame Seed Balls)',
        'type' => 'Snack',
        'calories' => 150,
        'protein' => 5.0,
        'carbs' => 12.0,
        'fats' => 10.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Sesame and coconut energy balls. Natural protein source.',
        'image' => 'images/thala_guli.jpg'
    ],
    [
        'name' => 'Kiri Toffee (Milk Toffee)',
        'type' => 'Snack',
        'calories' => 120,
        'protein' => 3.0,
        'carbs' => 18.0,
        'fats' => 4.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Creamy milk toffee with nuts. Popular Sri Lankan sweet.',
        'image' => 'images/kiri_toffee.jpg'
    ],
    [
        'name' => 'Wattalapam (Coconut Custard)',
        'type' => 'Dessert',
        'calories' => 280,
        'protein' => 8.0,
        'carbs' => 30.0,
        'fats' => 15.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Steamed coconut custard with jaggery. Traditional dessert.',
        'image' => 'images/wattalapam.jpg'
    ],
    [
        'name' => 'Kalu Dodol (Coconut Jaggery Sweet)',
        'type' => 'Dessert',
        'calories' => 220,
        'protein' => 3.0,
        'carbs' => 35.0,
        'fats' => 8.0,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 30,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Sticky coconut and jaggery sweet. Festive treat.',
        'image' => 'images/kalu_dodol.jpg'
    ],
    [
        'name' => 'Buffalo Curd with Treacle',
        'type' => 'Dessert',
        'calories' => 180,
        'protein' => 10.0,
        'carbs' => 20.0,
        'fats' => 7.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Creamy buffalo yogurt with palm treacle. Probiotic dessert.',
        'image' => 'images/buffalo_curd.jpg'
    ],
    [
        'name' => 'Fresh Fruit Platter',
        'type' => 'Snack',
        'calories' => 120,
        'protein' => 2.0,
        'carbs' => 28.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Diabetes',
        'activity_level' => 'Sedentary',
        'goal' => ['weight loss', 'detox'],
        'suggestion' => 'Seasonal tropical fruits. Natural vitamins and fiber.',
        'image' => 'images/fruit_platter.jpg'
    ],
    [
        'name' => 'Wood Apple Juice',
        'type' => 'Beverage',
        'calories' => 100,
        'protein' => 2.0,
        'carbs' => 22.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Constipation',
        'activity_level' => 'Sedentary',
        'goal' => ['detox', 'digestive health'],
        'suggestion' => 'Sweet and sour wood apple pulp drink. Aids digestion.',
        'image' => 'images/wood_apple_juice.jpg'
    ],
    [
        'name' => 'King Coconut Water',
        'type' => 'Beverage',
        'calories' => 60,
        'protein' => 2.0,
        'carbs' => 12.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Dehydration',
        'activity_level' => 'Sedentary',
        'goal' => ['hydration', 'detox'],
        'suggestion' => 'Natural electrolyte-rich coconut water. Refreshing and hydrating.',
        'image' => 'images/king_coconut.jpg'
    ],
    [
        'name' => 'Ginger Tea',
        'type' => 'Beverage',
        'calories' => 30,
        'protein' => 0.5,
        'carbs' => 6.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Cold/Flu',
        'activity_level' => 'Sedentary',
        'goal' => ['detox', 'immune boost'],
        'suggestion' => 'Spiced tea with fresh ginger. Good for digestion and immunity.',
        'image' => 'images/ginger_tea.jpg'
    ],

    // Beverages (10)
    [
        'name' => 'Ceylon Tea',
        'type' => 'Beverage',
        'calories' => 20,
        'protein' => 0.5,
        'carbs' => 4.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Sedentary',
        'goal' => ['hydration'],
        'suggestion' => 'World-famous Ceylon black tea. Antioxidant properties.',
        'image' => 'images/ceylon_tea.jpg'
    ],
    [
        'name' => 'Ginger Beer',
        'type' => 'Beverage',
        'calories' => 120,
        'protein' => 0.5,
        'carbs' => 28.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Fermented ginger beverage. Aids digestion.',
        'image' => 'images/ginger_beer.jpg'
    ],
    [
        'name' => 'Belimal (Wood Apple) Smoothie',
        'type' => 'Beverage',
        'calories' => 150,
        'protein' => 3.0,
        'carbs' => 30.0,
        'fats' => 2.0,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 33,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Constipation',
        'activity_level' => 'Lightly Active',
        'goal' => ['digestive health'],
        'suggestion' => 'Wood apple blended with honey. Natural digestive aid.',
        'image' => 'images/belimal_smoothie.jpg'
    ],
    [
        'name' => 'Papaya Juice',
        'type' => 'Beverage',
        'calories' => 90,
        'protein' => 1.0,
        'carbs' => 20.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Digestive Issues',
        'activity_level' => 'Sedentary',
        'goal' => ['digestive health', 'detox'],
        'suggestion' => 'Fresh papaya juice. Contains papain enzyme for digestion.',
        'image' => 'images/papaya_juice.jpg'
    ],
    [
        'name' => 'Nelli (Gooseberry) Juice',
        'type' => 'Beverage',
        'calories' => 80,
        'protein' => 1.0,
        'carbs' => 18.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Immunity Issues',
        'activity_level' => 'Sedentary',
        'goal' => ['immune boost', 'detox'],
        'suggestion' => 'Vitamin C-rich gooseberry juice. Immunity booster.',
        'image' => 'images/nelli_juice.jpg'
    ],
    [
        'name' => 'Mango Juice',
        'type' => 'Beverage',
        'calories' => 110,
        'protein' => 1.0,
        'carbs' => 25.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Seasonal mango juice. Rich in vitamin A and C.',
        'image' => 'images/mango_juice.jpg'
    ],
    [
        'name' => 'Pineapple Juice',
        'type' => 'Beverage',
        'calories' => 100,
        'protein' => 1.0,
        'carbs' => 22.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Digestive Issues',
        'activity_level' => 'Lightly Active',
        'goal' => ['digestive health'],
        'suggestion' => 'Fresh pineapple juice. Contains bromelain enzyme for digestion.',
        'image' => 'images/pineapple_juice.jpg'
    ],
    [
        'name' => 'Watermelon Juice',
        'type' => 'Beverage',
        'calories' => 70,
        'protein' => 1.0,
        'carbs' => 16.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Hydration',
        'activity_level' => 'Sedentary',
        'goal' => ['hydration', 'detox'],
        'suggestion' => 'Refreshing watermelon juice. High water content for hydration.',
        'image' => 'images/watermelon_juice.jpg'
    ],
    [
        'name' => 'Lime Juice',
        'type' => 'Beverage',
        'calories' => 40,
        'protein' => 0.5,
        'carbs' => 10.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 80,
        'max_bmi' => 35,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Immunity Issues',
        'activity_level' => 'Sedentary',
        'goal' => ['immune boost', 'detox'],
        'suggestion' => 'Fresh lime juice with honey. Vitamin C rich beverage.',
        'image' => 'images/lime_juice.jpg'
    ],
    [
        'name' => 'Jaggery Tea',
        'type' => 'Beverage',
        'calories' => 60,
        'protein' => 0.5,
        'carbs' => 14.0,
        'fats' => 0.5,
        'min_age' => 18,
        'max_age' => 75,
        'max_bmi' => 32,
        'gender' => ['Male', 'Female'],
        'disease' => 'Vegetarian, Vegan, Anemia',
        'activity_level' => 'Lightly Active',
        'goal' => ['maintenance'],
        'suggestion' => 'Tea sweetened with unrefined jaggery. Natural iron source.',
        'image' => 'images/jaggery_tea.jpg'
    ]
];
?>